specfile_path: oval-graph.spec
synced_files:
  # copy a file from root of the upstream repo to dist-git
  - oval-graph.spec
upstream_package_name: oval_graph
downstream_package_name: oval-graph
upstream_project_url: https://github.com/OpenSCAP/OVAL-visualization-as-graph

# the version is different than with basic git describe
create_tarball_command: ["python3", "setup.py", "sdist", "--dist-dir", "."]
current_version_command: ["python3", "setup.py", "--version"]
jobs:
- job: sync_from_downstream
  trigger: commit

- job: propose_downstream
  trigger: release
  metadata:
    dist-git-branch: fedora-all

- job: propose_downstream
  trigger: release
  metadata:
    dist-git-branch: epel7

- job: propose_downstream
  trigger: release
  metadata:
    dist-git-branch: epel8

- job: propose_downstream
  trigger: release
  metadata:
    dist-git-branch: epel8-playground

- job: copr_build
  trigger: pull_request
  metadata:
    targets:
    - fedora-all
    - epel-7-x86_64
    - epel-8-x86_64

- job: tests
  trigger: pull_request
  metadata:
    targets:
    - fedora-all
# Disabled EPEL 7 install test because for install is used dnf on CentOS 7 
    - epel-7-x86_64
    - epel-8-x86_64
